"""empty message

Revision ID: 37523a8b2105
Revises: f008fa1b5b7d
Create Date: 2019-02-28 14:38:25.150015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37523a8b2105'
down_revision = 'f008fa1b5b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('publishdate', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
